manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Cyboard-DigitalTailor
      url-base: https://github.com/Cyboard-DigitalTailor
    - name: urob
      url-base: https://github.com/urob
    - name: darknao

  projects:

    - name: zmk-keyboards
      remote: Cyboard-DigitalTailor
      revision: main
      import: config/west.yml

    # urob modules
    - name: zmk-adaptive-key
      remote: urob
      revision: main
      path: modules/zmk/adaptive-key

  self:
    path: config
